"""
Demonstration program for List functions
"""
list=[1,3,4,5,6]
print(list)
print(f"length of the list is {len(list)!s}")
#print(list(range(len(list))))
print("2 is missing; let's fix that")
#adding 2 in position
list.insert(1,2)
print(list)
print("Let's add 7")
list.append(7)
print(list)
print(list.pop())
print(list)
print("7 popped out")
print(f"{list.pop(1)!s} popped out too")
print(list)
list.extend([3,4,5])
print(list)
print("List extended")
list.remove(3)
print("3 removed")
print(list)
print(f"{list.index(4,4)!s} - position of second 4")
print(f"{list.count(4)!s} -  count of 4")
list.sort()
print("Sorted list")
print(list)
list.reverse()
print("Reversed list")
print(list)
list.clear()
print(list)
print("List is empty")
